 SELECT [ACCOUNTNUMBER]
      ,[ACCOUNTTYPECODE]
      ,[ACCOUNTTYPE]
      ,[ZONE_DIVISONCODE]
      ,[ZONE_DIVISION]
      ,[METERNUMBER]
      ,[REGISTERNUMBER]
      ,[CONSUMPTION]
      ,[UNITS]
      ,[READINGDATE]
      ,[READINGMONTH]
      ,[READINGDAY]
      ,[READINGYEAR]
      ,[READINGDAYSCOUNT]
      ,CONCAT([BIF002].[N_STREETNUM], ' ', IIF([BIF002].[C_STREETPREFIX] IS NULL,'', [BIF002].[C_STREETPREFIX]),' ',[BIF002].[C_STREET],' ',[BIF002].[C_STREETSUFFIX]) AS STREETADDRESS
    ,MEF321.C_LOCATION AS DEVICELOCATION
  FROM [water].[dbo].[Consumption_By_Account]
   INNER JOIN CISInfinity.ADVANCED.BIF003 ON water.dbo.Consumption_By_Account.ACCOUNTNUMBER = CISInfinity.ADVANCED.BIF003.C_ACCOUNT
    INNER JOIN CISInfinity.ADVANCED.BIF002 ON water.dbo.Consumption_By_Account.ACCOUNTNUMBER = CISInfinity.ADVANCED.BIF002.C_ACCOUNT
    LEFT JOIN CISInfinity.ADVANCED.BIF310 ON water.dbo.Consumption_By_Account.ACCOUNTNUMBER = CISInfinity.ADVANCED.BIF310.C_ACCOUNT
   LEFT JOIN CISInfinity.ADVANCED.MEF321 ON CISInfinity.ADVANCED.BIF310.C_DEVICE = CISInfinity.ADVANCED.MEF321.C_DEVICE
  WHERE ACCOUNTNUMBER = @AccountNumber AND CISInfinity.ADVANCED.BIF003.C_ACCOUNTSTATUS = 'AC' AND READINGDATE > CISInfinity.ADVANCED.BIF003.D_MOVEIN
  ORDER BY READINGDATE DESC
